/**
 * Auth actions
 */
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';

/**
 * Message actions
 */
export const GET_CHAT_LIST_LOADING = 'GET_CHAT_LIST_LOADING';
export const GET_CHAT_LIST_SUCCESS = 'GET_CHAT_LIST_SUCCESS';
export const GET_CHAT_LIST_FAIL = 'GET_CHAT_LIST_FAIL';

export const GET_CONTENT_MESS_LOADING = 'GET_CONTENT_MESS_LOADING';
export const GET_CONTENT_MESS_SUCCESS = 'GET_CONTENT_MESS_SUCCESS';
export const GET_CONTENT_MESS_FAIL = 'GET_CONTENT_MESS_FAIL';
export const DELETE_CACHE_MESS = 'DELETE_CACHE_MESS';

export const SEND_MESS_SUCCESS = 'SEND_MESS_SUCCESS';
export const SEND_MESS_FAIL = 'SEND_MESS_FAIL';

/**
 * Contact actions
 */
export const GET_LIST_CONTACTS_LOADING = 'GET_LIST_CONTACTS_LOADING';
export const GET_LIST_CONTACTS_SUCCESS = 'GET_LIST_CONTACTS_SUCCESS';
export const GET_LIST_CONTACTS_FAIL = 'GET_LIST_CONTACTS_FAIL';

export const GET_FRIEND_REQUESTS_LOADING = 'GET_FRIEND_REQUESTS_LOADING';
export const GET_FRIEND_REQUESTS_SUCCESS = 'GET_FRIEND_REQUESTS_SUCCESS';
export const GET_FRIEND_REQUESTS_FAIL = 'GET_FRIEND_REQUESTS_FAIL';

export const SET_ACCEPT_REQUEST_LOADING = 'SET_ACCEPT_REQUEST_LOADING';
export const SET_ACCEPT_REQUEST_SUCCESS = 'SET_ACCEPT_REQUEST_SUCCESS';
export const SET_ACCEPT_REQUEST_FAIL = 'SET_ACCEPT_REQUEST_FAIL';

export const ADD_FRIEND_BY_ID_LOADING = 'ADD_FRIEND_BY_ID_LOADING';
export const ADD_FRIEND_BY_ID_SUCCESS = 'ADD_FRIEND_BY_ID_SUCCESS';
export const ADD_FRIEND_BY_ID_FAIL = 'ADD_FRIEND_BY_ID_FAIL';
export const CLEAR_ADD_FRIEND_BY_ID_STATE = 'CLEAR_ADD_FRIEND_BY_ID_STATE';

export const GET_CONTACT_BY_PHONE_LOADING = 'GET_CONTACT_BY_PHONE_LOADING';
export const GET_CONTACT_BY_PHONE_SUCCESS = 'GET_CONTACT_BY_PHONE_SUCCESS';
export const GET_CONTACT_BY_PHONE_FAIL = 'GET_CONTACT_BY_PHONE_FAIL';
export const CLEAR_GET_CONTACT_BY_PHONE_STATE = 'CLEAR_GET_CONTACT_BY_PHONE_STATE';

/**
 * Post actions
 */
export const GET_LIST_POSTS_LOADING = 'GET_LIST_POSTS_LOADING';
export const GET_LIST_POSTS_SUCCESS = 'GET_LIST_POSTS_SUCCESS';
export const GET_LIST_POSTS_FAIL = 'GET_LIST_POSTS_FAIL';

export const GET_MY_POSTS_LOADING = 'GET_MY_POSTS_LOADING';
export const GET_MY_POSTS_SUCCESS = 'GET_MY_POSTS_SUCCESS';
export const GET_MY_POSTS_FAIL = 'GET_MY_POSTS_FAIL';

export const CREATE_NEW_POST_LOADING = 'CREATE_NEW_POST_LOADING';
export const CREATE_NEW_POST_SUCCESS = 'CREATE_NEW_POST_SUCCESS';
export const CREATE_NEW_POST_FAIL = 'CREATE_NEW_POST_FAIL';

export const DELETE_POST_LOADING = 'DELETE_POST_LOADING';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const GET_LIST_COMMENTS_LOADING = 'GET_LIST_COMMENTS_LOADING';
export const GET_LIST_COMMENTS_SUCCESS = 'GET_LIST_COMMENTS_SUCCESS';
export const GET_LIST_COMMENTS_FAIL = 'GET_LIST_COMMENTS_FAIL';
export const CLEAR_LIST_COMMENTS_STATE = 'CLEAR_LIST_COMMENTS_STATE';

export const CREATE_COMMENT_LOADING = 'CREATE_COMMENT_LOADING';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

/**
 * Channel actions
 */
